import { POSITION, ORIENTATION } from '../constants';

/**
 * @exports {Object} the map of shift positions
 */
export default {
    [ORIENTATION.VERTICAL]: {
        [POSITION.TOP]: POSITION.BOTTOM,
        [POSITION.TOP_RIGHT]: POSITION.BOTTOM_RIGHT,
        [POSITION.TOP_LEFT]: POSITION.BOTTOM_LEFT,
        [POSITION.RIGHT]: POSITION.RIGHT,
        [POSITION.RIGHT_TOP]: POSITION.RIGHT_BOTTOM,
        [POSITION.RIGHT_BOTTOM]: POSITION.RIGHT_TOP,
        [POSITION.LEFT]: POSITION.LEFT,
        [POSITION.LEFT_TOP]: POSITION.LEFT_BOTTOM,
        [POSITION.LEFT_BOTTOM]: POSITION.LEFT_TOP,
        [POSITION.BOTTOM]: POSITION.TOP,
        [POSITION.BOTTOM_RIGHT]: POSITION.TOP_RIGHT,
        [POSITION.BOTTOM_LEFT]: POSITION.TOP_LEFT,
    },
    [ORIENTATION.HORIZONTAL]: {
        [POSITION.TOP]: POSITION.TOP,
        [POSITION.TOP_RIGHT]: POSITION.TOP_LEFT,
        [POSITION.TOP_LEFT]: POSITION.TOP_RIGHT,
        [POSITION.RIGHT]: POSITION.LEFT,
        [POSITION.RIGHT_TOP]: POSITION.LEFT_TOP,
        [POSITION.RIGHT_BOTTOM]:POSITION.LEFT_BOTTOM,
        [POSITION.LEFT]: POSITION.RIGHT,
        [POSITION.LEFT_TOP]: POSITION.RIGHT_TOP,
        [POSITION.LEFT_BOTTOM]: POSITION.RIGHT_BOTTOM,
        [POSITION.BOTTOM]: POSITION.BOTTOM,
        [POSITION.BOTTOM_RIGHT]: POSITION.BOTTOM_LEFT,
        [POSITION.BOTTOM_LEFT]: POSITION.BOTTOM_RIGHT,
    },
}
