#!/usr/bin/env bash
set -e

if [ "$TRAVIS_BRANCH" == "master" ]; then
    # this is a "pr" job for travis-ci, run the full saucelabs suite
    npm run test:regression
else
    # this is a "push" job for travis-ci, keep it short and sweet
    cd ..
    # npm run lint
    npm run apidocs
    npm run generate
    npm run rollup
    cd -
    npm run build
    npm run lint
fi
