#!/usr/bin/env bash

# https://stackoverflow.com/a/4785518/881224
which wget >/dev/null 2>&1 || { echo "Install wget and try again. Aborting." >&2; exit 1; }

# remove sources
find bin/selenium/. ! -name '.gitignore' -type f -exec rm -f {} +
# remove symlinks
rm -f node_modules/.bin/{gecko,chromedriver,selenium}*

platform_gecko='linux64'
platform_chrome='linux64'
[ `uname` == 'Darwin' ] && platform_gecko='macos' && platform_chrome='mac64'

TARFILE_GECKO=v0.18.0/geckodriver-v0.18.0-${platform_gecko}.tar.gz
TARFILE_CHROME=2.31/chromedriver_${platform_chrome}.zip
TARFILE_STANDALONE='3.4/selenium-server-standalone-3.4.0.jar'

echo Downloading ${TARFILE_GECKO}
wget -nc -q https://{GH_TOKEN}@github.com/mozilla/geckodriver/releases/download/${TARFILE_GECKO} -O bin/selenium/geckodriver-v0.18.0.tar.gz
echo Downloading ${TARFILE_CHROME}
wget -nc -q https://chromedriver.storage.googleapis.com/${TARFILE_CHROME} -O bin/selenium/chromedriver_2.31.zip
echo Downloading ${TARFILE_STANDALONE}
wget -nc -q https://selenium-release.storage.googleapis.com/${TARFILE_STANDALONE} -O bin/selenium/selenium-server-standalone.jar
tar -xzf bin/selenium/geckodriver-v0.18.0.tar.gz -C bin/selenium/
unzip -o bin/selenium/chromedriver_2.31.zip -d bin/selenium/
cd node_modules/.bin/ && ln -s ../../bin/selenium/* .
