#!/usr/bin/env bash

# https://stackoverflow.com/a/4785518/881224
LINK="https://github.com/HelixDesignSystem/helix-ui/wiki/Testing#java"
which java >/dev/null 2>&1 || { echo ${LINK}; echo "Install java and try again. Aborting." >&2; exit 1; }

java -Dwebdriver.gecko.driver=bin/selenium/geckodriver \
     -Dwebdriver.chrome.driver=bin/selenium/chromedriver \
     -jar bin/selenium/selenium-server-standalone.jar \
     -port 4444
