# Helix-UI CI Pipeline - GitHub Actions Workflow

name: HelixUI CI Build Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Pull Request or Push Action

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: HelixUI Build and Test
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x

      - run: npm install -g yarn
      - run: yarn install:clean
      - run: yarn lint
      - run: yarn generate
      - run: yarn test:build
